Repository 2201gh-team-saturn/grace-shopper-main, pull requests merged in 2022-03, with the labels that each got.

#22 fixed associations
  server/db/index.js
Labels: bug

#24 barebones seed file for others to use as well
  script/seed.js
Labels: good first issue

#33 All experiences redux
  client/components/Experiences.js
  client/store/experiences.js
Labels: enhancement

#30 Leahs seed
  script/seed.js
Labels: enhancement

#41 seed file complete
  script/seed.js
Labels: good first issue

#49 Leah WED night
  client/Routes.js
  client/components/Experiences.js
  client/store/experiences.js
  client/store/index.js
  server/api/experiences.js
  server/api/rooms.js
Labels: enhancement

#59 fixed single experience bug
  client/Routes.js
  client/components/SingleExperience.js
  client/store/singleExperience.js
  seededData.js
Labels: bug

#61 some css work in single room
  public/style.css
Labels: enhancement

#79 fixed case error found in cart model while trying to deploy heroku
  server/api/cart.js
Labels: bug

#95 Cart component and cart updates
  client/Routes.js
  client/components/Cart.js
  client/components/Navbar.js
  client/components/SingleRoom.js
  client/components/UpdateSingleRoom.js
  client/store/singleRoom.js
  script/seed.js
  server/api/cart.js
  server/db/index.js
  server/db/models/Cart.js
  server/db/models/CartItem.js
Labels: bug, enhancement

#98 finally getting a protected cart route up and running !!
  client/components/Cart.js
  client/store/shopping_cart.js
  server/api/cart.js
  server/api/users.js
  server/auth/index.js
  server/db/models/User.js
Labels: bug, good first issue

#118 Cart Association updates
  server/api/cart.js
  server/db/index.js
Labels: bug, enhancement

#129 work on add to cart and local state guest cart functionality
  client/App.js
  client/components/GuestCart.js
  client/components/SingleRoom.js
  client/store/shopping_cart.js
  server/api/cart.js
  server/api/experiences.js
Labels: enhancement, good first issue

#122 edit cart bug
  client/components/AllRooms.js
  client/components/Cart.js
  client/components/UpdateCart.js
  client/store/cartItems.js
  client/store/experiences.js
  client/store/shopping_cart.js
  server/api/cart.js
Labels: bug

#130 added handleCheckout function in cart component
  client/components/Cart.js
Labels: good first issue

#147 Final push from kelsey
  client/App.js
  client/Routes.js
  client/components/AllRooms.js
  client/components/GuestCart.js
  client/components/SingleRoom.js
  client/store/cartItems.js
  client/store/shopping_cart.js
  script/seed.js
  server/api/cart.js
Labels: bug, enhancement
